version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: github.com/natanista/go-api
    container_name: go-api-db
    restart: unless-stopped
    tty: true
    ports:
      - "25431:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/go-api
    volumes:
      - go-api:/var/lib/postgresql/data

volumes:
  go-api:
