version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .Dockerfile
    image: github.com/natanista/go-api
    container_name: go-api
    restart: unless-stopped
    tty: true
    ports:
      - "25431:5432"
    environment:
      DATABASE_DBNAME: books
      DATABASE_PORT: 5432
      DATABASE_HOST: localhost
      DATABASE_USER: admin
      DATABASE_DIALECT: postgresql
      DATABASE_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/go-api
    volumes:
      - go-api:/var/lib/postgresql/data

volumes:
  go-api:
