apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      containers:
        - name: goapi
          image: natanista/natanista-hub:goapi
          env:
            - name: DB_DBNAME
              value: "books"
            - name: DB_URL
              value: "goapi-postgres:5432/docker"
            - name: DB_HOST
              value: "goapi-postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: goapi-postgres-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: goapi-postgres-db-secret
                  key: password
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: goapi
spec:
  type: NodePort
  selector:
    app: goapi
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Secret
metadata:
  name: goapi-postgres-db-secret
data:
  username: YWRtaW4=
  password: MTIzNDU2
